module.exports = {
  DEALER_APPLICATION: 'dealer:application',
  DEALER_APPROVED: 'dealer:approved',
  DEALER_REJECTED: 'dealer:rejected',
  DEALER_SUSPENDED: 'dealer:suspended',
  ORDER_CONFIRMED: 'order:confirmed',
  ORDER_CANCELLED: 'order:cancelled',
  PAYMENT_CONFIRMED: 'payment:confirmed',
  RETURN_PROCESSED: 'return:processed',
  LOW_STOCK_ALERT: 'inventory:low_stock',
  PRODUCT_CREATED: 'product:created',
  PRODUCT_UPDATED: 'product:updated',
  NEW_NOTIFICATION: 'notification:new',
  KPI_UPDATE: 'dashboard:kpi_update',
  INVOICE_OVERDUE: 'invoice:overdue',
  WARRANTY_NEW_CLAIM: 'warranty:new_claim',
  WARRANTY_STATUS_UPDATED: 'warranty:status_updated',
  ECOMMERCE_NEW_ORDER: 'ecommerce:new_order',
  ENQUIRY_NEW: 'enquiry:new',
};
